#! /usr/bin/python

import argparse
import re


# Time Regex: ^([0-9]+)((s|ms)|((\.\d)(s|ms)))$
# Starts with any number of digits. Must be follwed by either 's'/'ms'
# or a decimal point ('.'), one digit, and then 's'/'ms'.
def valid_time(time):
    """
    Parses the time/move command line argument to make sure it passes a
    correctly formatted time. Acceptable times match any of these formats:
        2s
        2.0s
        2000ms
        2000.0ms

    Passing an invalid time format will result in an ArgumentTypeError.
    Passing a correct format will return the time string.

    """
    p = re.compile('^([0-9]+)((s|ms)|((\.\d)(s|ms)))$')
    if p.match(time):
        return time
    else:
        raise argparse.ArgumentTypeError('is not a correct format')

def init_argparser():
    """
    Initializes the ArgumentParser. Allows the two arguments:
        --go <n>
        --time/move <t>

    Parses the arguments to match all required software specifications,
    and prints error messages to standard out.

    """
    parser = argparse.ArgumentParser(
        usage='./%(prog)s --go <n> --time/move <t>',
        description='Luzhanqi.'
    )
    parser.add_argument(
        '--go',
        type=int,
        choices=[1, 2],
        required=True,
        help='Whether the player goes first or second',
        dest='player'
    )
    parser.add_argument(
        '--time/move',
        type=valid_time,
        required=True,
        help='Time alloted per turn',
        dest='time'
    )

    args = parser.parse_args()
    return args.player, args.time

if __name__ == '__main__':
    player, time = init_argparser()
    print player
    print time
